Public Class GM_Drug_Columns

    Public Const COLUMN_NAME_GDRG_HotCode As String = "HOT9コード"
    Public Const COLUMN_NAME_GDRG_LogNo As String = "履歴番号"
    Public Const COLUMN_NAME_GDRG_UpdateDate As String = "更新日時"
    Public Const COLUMN_NAME_GDRG_UpdateClientName As String = "更新端末名"
    Public Const COLUMN_NAME_GDRG_UpdateStaffID As String = "更新職員ID"
    Public Const COLUMN_NAME_GDRG_DelFlag As String = "削除フラグ"
    Public Const COLUMN_NAME_GDRG_ValidDateFrom As String = "有効開始日"
    Public Const COLUMN_NAME_GDRG_ValidDateTo As String = "有効終了日"
    Public Const COLUMN_NAME_GDRG_ReceiptCode As String = "医薬品コード"
    Public Const COLUMN_NAME_GDRG_StandardCode As String = "基準番号(HOT番号)"
    Public Const COLUMN_NAME_GDRG_MHLWCode As String = "薬価基準コード"
    Public Const COLUMN_NAME_GDRG_PublicCode As String = "一般名コード"
    Public Const COLUMN_NAME_GDRG_DrugName As String = "漢字名称"
    Public Const COLUMN_NAME_GDRG_DrugKana As String = "カナ名称"
    Public Const COLUMN_NAME_GDRG_SalesName As String = "販売名"
    Public Const COLUMN_NAME_GDRG_PublicName As String = "一般名"
    Public Const COLUMN_NAME_GDRG_ComponentName As String = "成分名"
    Public Const COLUMN_NAME_GDRG_OriginalName As String = "先発品名"
    Public Const COLUMN_NAME_GDRG_DisplayDrugName As String = "表示用薬品名"
    Public Const COLUMN_NAME_GDRG_SearchKeyword As String = "検索キーワード"
    Public Const COLUMN_NAME_GDRG_UnitInit As String = "オーダ初期表示単位"
    Public Const COLUMN_NAME_GDRG_UnitReceipt As String = "医事算定単位"
    Public Const COLUMN_NAME_GDRG_UnitPharm As String = "調剤送信単位"
    Public Const COLUMN_NAME_GDRG_NarcoticClass As String = "麻毒区分"
    Public Const COLUMN_NAME_GDRG_DosageFormClass As String = "剤形区分"
    Public Const COLUMN_NAME_GDRG_DrugFormType As String = "薬品形態種別"
    Public Const COLUMN_NAME_GDRG_Syringeful As String = "注射容量"
    Public Const COLUMN_NAME_GDRG_TransfusionUnit As String = "輸血製材単位"
    Public Const COLUMN_NAME_GDRG_UsageCode As String = "処方標準用法"
    Public Const COLUMN_NAME_GDRG_ExternalPartCode As String = "外用部位コード"
    Public Const COLUMN_NAME_GDRG_DosageClass As String = "用量指示区分"
    Public Const COLUMN_NAME_GDRG_DoseTimes As String = "頓服回数"
    Public Const COLUMN_NAME_GDRG_DoseDays As String = "投与日数"
    Public Const COLUMN_NAME_GDRG_IntervalDays As String = "隔日日数"
    Public Const COLUMN_NAME_GDRG_Dosage As String = "用量"
    Public Const COLUMN_NAME_GDRG_OnceMaxDosage As String = "1回MAX量"
    Public Const COLUMN_NAME_GDRG_DailyMaxDosage As String = "1日MAX量"
    Public Const COLUMN_NAME_GDRG_AdoptClass As String = "採用区分"
    Public Const COLUMN_NAME_GDRG_OrderMedicineFlag As String = "処方オーダ対象フラグ"
    Public Const COLUMN_NAME_GDRG_OrderInjectionFlag As String = "注射オーダ対象フラグ"
    Public Const COLUMN_NAME_GDRG_OrderTransfusionFlag As String = "輸血オーダ対象フラグ"
    Public Const COLUMN_NAME_GDRG_NerveDestroyFlag As String = "神経破壊剤フラグ"
    Public Const COLUMN_NAME_GDRG_BiologyFlag As String = "生物学的製剤フラグ"
    Public Const COLUMN_NAME_GDRG_GenericFlag As String = "後発品フラグ"
    Public Const COLUMN_NAME_GDRG_DentistrySpecialtyFlag As String = "歯科特定医薬品フラグ"
    Public Const COLUMN_NAME_GDRG_ContrastMediumFlag As String = "造影(補助)剤フラグ"
    Public Const COLUMN_NAME_GDRG_GrindFlag As String = "粉砕フラグ"
    Public Const COLUMN_NAME_GDRG_MixFlag As String = "混合フラグ"
    Public Const COLUMN_NAME_GDRG_DissolveFlag As String = "溶解フラグ"
    Public Const COLUMN_NAME_GDRG_PTPFlag As String = "PTPフラグ"
    Public Const COLUMN_NAME_GDRG_OneDosePackagFlag As String = "一包化フラグ"
    Public Const COLUMN_NAME_GDRG_HospitalPreparationFlag As String = "院内製剤フラグ"
    Public Const COLUMN_NAME_GDRG_INDFlag As String = "治験薬フラグ"
    Public Const COLUMN_NAME_GDRG_ExtraDrugFlag As String = "臨時薬フラグ"
    Public Const COLUMN_NAME_GDRG_DiabetesFlag As String = "糖尿病薬フラグ"
    Public Const COLUMN_NAME_GDRG_AnticancerDrugFlag As String = "抗癌薬フラグ"
    Public Const COLUMN_NAME_GDRG_SubstituteHotCode1 As String = "代替医薬品HOT9コード1"
    Public Const COLUMN_NAME_GDRG_SubstituteHotCode2 As String = "代替医薬品HOT9コード2"
    Public Const COLUMN_NAME_GDRG_LabelPrintFlag As String = "ラベル印刷対象フラグ 1=印刷対象"
    Public Const COLUMN_NAME_GDRG_PatientLimitedFlag As String = "患者限定採用フラグ 1=患者限定採用"
    Public Const COLUMN_NAME_GDRG_Remarks As String = "備考"

End Class
