'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class T_PaymentHeader
    Public Property PaymentNo As String
    Public Property SupplierCd As String
    Public Property PaymentDate As Nullable(Of Date)
    Public Property InvoiceAmount As Nullable(Of Decimal)
    Public Property PaymentAmount As Nullable(Of Decimal)
    Public Property Deduction As Nullable(Of Decimal)
    Public Property InsertedBy As String
    Public Property InsertedAt As Nullable(Of Date)
    Public Property UpdatedBy As String
    Public Property UpdatedAt As Nullable(Of Date)

End Class
