Public Class CM_Drug_Columns

    Public Const COLUMN_NAME_CDRG_StandardCode As String = "基準番号(HOT番号)"
    Public Const COLUMN_NAME_CDRG_JANCode As String = "JANコード"
    Public Const COLUMN_NAME_CDRG_PackUnit As String = "包装単位単位"
    Public Const COLUMN_NAME_CDRG_PackTotalUnit As String = "包装総量単位"
    Public Const COLUMN_NAME_CDRG_MakerCompany As String = "製造会社"
    Public Const COLUMN_NAME_CDRG_SalesCompany As String = "販売会社"
    Public Const COLUMN_NAME_CDRG_Hot7Code As String = "処方用番号(HOT7)"
    Public Const COLUMN_NAME_CDRG_CompanyCode As String = "会社識別番号"
    Public Const COLUMN_NAME_CDRG_ReceiptCode As String = "医薬品コード"
    Public Const COLUMN_NAME_CDRG_MhlwCode As String = "薬価基準コード"
    Public Const COLUMN_NAME_CDRG_IndividualCode As String = "個別医薬品コード"
    Public Const COLUMN_NAME_CDRG_PublicCode As String = "一般名コード"
    Public Const COLUMN_NAME_CDRG_DrugName As String = "漢字名称"
    Public Const COLUMN_NAME_CDRG_DrugKana As String = "カナ名称"
    Public Const COLUMN_NAME_CDRG_SalesName As String = "販売名"
    Public Const COLUMN_NAME_CDRG_PublicName As String = "一般名"
    Public Const COLUMN_NAME_CDRG_ComponentName As String = "成分名"
    Public Const COLUMN_NAME_CDRG_OriginalName As String = "先発薬品名"
    Public Const COLUMN_NAME_CDRG_UnitCode As String = "単位コード"
    Public Const COLUMN_NAME_CDRG_NarcoticClass As String = "麻薬・毒薬・覚せい剤原料・向精神薬"
    Public Const COLUMN_NAME_CDRG_DosageFormClass As String = "剤形"
    Public Const COLUMN_NAME_CDRG_Syringeful As String = "注射容量"
    Public Const COLUMN_NAME_CDRG_NerveDestroyFlag As String = "神経破壊剤"
    Public Const COLUMN_NAME_CDRG_BiologyFlag As String = "生物学的製剤"
    Public Const COLUMN_NAME_CDRG_GenericFlag As String = "後発品"
    Public Const COLUMN_NAME_CDRG_DentistrySpecialtyFlag As String = "歯科特定医薬品"
    Public Const COLUMN_NAME_CDRG_ContrastMediumFlag As String = "造影（補助）剤"
    Public Const COLUMN_NAME_CDRG_ValidDateFrom As String = "変更年月日"
    Public Const COLUMN_NAME_CDRG_ValidDateTo As String = "廃止年月日"

End Class
