'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class M_Item
    Public Property ItemCd As String
    Public Property ItemName As String
    Public Property Season As String
    Public Property MakerCd As String
    Public Property SizeTypeCd As String
    Public Property ColorTypeCd As String
    Public Property RetailPrice As Nullable(Of Decimal)
    Public Property CostPrice As Nullable(Of Decimal)
    Public Property InsertedBy As String
    Public Property InsertedAt As Nullable(Of Date)
    Public Property UpdatedBy As String
    Public Property UpdatedAt As Nullable(Of Date)

    Public Overridable Property M_ColorType As M_ColorType
    Public Overridable Property M_SizeType As M_SizeType

End Class
