'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AspNetRoles
    Public Property Id As String
    Public Property Name As String

    Public Overridable Property AspNetUsers As ICollection(Of AspNetUsers) = New HashSet(Of AspNetUsers)

End Class
