'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class M_SizeType
    Public Property SizeTypeCd As String
    Public Property SizeTypeName As String
    Public Property InsertedBy As String
    Public Property InsertedAt As Nullable(Of Date)
    Public Property UpdatedBy As String
    Public Property UpdatedAt As Nullable(Of Date)
    Public Property SortNo As Nullable(Of Byte)

    Public Overridable Property M_Size As ICollection(Of M_Size) = New HashSet(Of M_Size)
    Public Overridable Property M_Item As ICollection(Of M_Item) = New HashSet(Of M_Item)

End Class
