'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class T_HachuHeader
    Public Property HachuNo As String
    Public Property SupplierCd As String
    Public Property HachuDate As Nullable(Of Date)
    Public Property HachuAmount As Nullable(Of Decimal)
    Public Property OrderNo As String

End Class
