'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class T_InvoiceHeader
    Public Property InvoiceNo As String
    Public Property CustomerCd As String
    Public Property InvoiceDate As Nullable(Of Date)
    Public Property InsertedBy As String
    Public Property InsertedAt As Nullable(Of Date)
    Public Property UpdatedBy As String
    Public Property UpdatedAt As Nullable(Of Date)

End Class
