'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class T_JuchuHeader
    Public Property JuchuNo As String
    Public Property CustomerCd As String
    Public Property JuchuDate As Nullable(Of Date)

    Public Overridable Property M_Customer As M_Customer

End Class
