'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class M_StaffBase
    Public Property MSTB_StaffID As String
    Public Property MSTB_LogNo As Integer
    Public Property MSTB_UpdateDate As Date
    Public Property MSTB_UpdateClientName As String
    Public Property MSTB_UpdateStaffID As String
    Public Property MSTB_DelFlag As Integer
    Public Property MSTB_NameKana As String
    Public Property MSTB_Name As String
    Public Property MSTB_BirthDate As Nullable(Of Date)
    Public Property MSTB_SexType As String
    Public Property MSTB_EnterDate As Nullable(Of Date)
    Public Property MSTB_RetireDate As Nullable(Of Date)
    Public Property MSTB_Remarks As String

End Class
